<a href="https://colab.research.google.com/github/vasuaw/TensorFlow/blob/main/00tensorflow_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Introduction to Tensorflow**

Import Tensorflow and run

In [ ]:
## import tensorflow
import tensorflow as tf
print(tf.__version__)

2.8.2


In [ ]:
## creating tensors with tf.constant
scalar=tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [ ]:
scalar.ndim

0

In [ ]:
## creating a vector
vector=tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [ ]:
vector.ndim

1

In [ ]:
## creating a matrix
matrix=tf.constant([[1,2,3.],[4,6,4]])
matrix

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[1., 2., 3.],
       [4., 6., 4.]], dtype=float32)>

In [ ]:
another_matrix=tf.constant([[4,5,6],[4,7.,8.]], dtype=tf.float16)
another_matrix

<tf.Tensor: shape=(2, 3), dtype=float16, numpy=
array([[4., 5., 6.],
       [4., 7., 8.]], dtype=float16)>

In [ ]:
matrix.ndim, another_matrix.ndim

(2, 2)

In [ ]:
## creating a tensor
tensor=tf.constant([[[10,4],[4,6]],
                    [[7,5],[5,6]],
                    [[4,99],[43,21]]])
tensor

<tf.Tensor: shape=(3, 2, 2), dtype=int32, numpy=
array([[[10,  4],
        [ 4,  6]],

       [[ 7,  5],
        [ 5,  6]],

       [[ 4, 99],
        [43, 21]]], dtype=int32)>

In [ ]:
tensor.ndim

3

Vector - 1D with directions
Scalar - number
Matrix - 2D
Tensor - nD

Creating tensor using tf.variable

In [ ]:
change_tensor= tf.Variable([10,7])
unchange_tensor=tf.constant([10,7])
change_tensor, unchange_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [ ]:
# using asign variable
change_tensor[0].assign(7)

<tf.Variable 'UnreadVariable' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

In [ ]:
unchange_tensor[0].assign(7)

AttributeError: ignored

In [ ]:
##.variable can change but constant cannot change

In [ ]:
## Creating Random Tensors
random_tensor= tf.random.Generator.from_seed(7)
random_tensor=random_tensor.normal(shape=(3,2))
random_tensor2=tf.random.Generator.from_seed(7)
random_tensor2=random_tensor2.normal(shape=(3,2))
random_tensor, random_tensor2, random_tensor==random_tensor2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-1.3240396 ,  0.28785667],
        [-0.8757901 , -0.08857018],
        [ 0.69211644,  0.84215707]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-1.3240396 ,  0.28785667],
        [-0.8757901 , -0.08857018],
        [ 0.69211644,  0.84215707]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

In [ ]:
## Shufling the order of elements Tensors

In [ ]:
tensor_random3= tf.constant([[3,4],[5,6],[6,7]])
tensor_random3

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[3, 4],
       [5, 6],
       [6, 7]], dtype=int32)>

In [ ]:
tf.random.shuffle(tensor_random3)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[5, 6],
       [3, 4],
       [6, 7]], dtype=int32)>

In [ ]:
## Exercise for random seed- Global and operational Seed
tensor_random4=tf.random.Generator.from_seed(42)
tensor_random4=tensor_random4.normal(shape=(2,4))
tensor_random4

<tf.Tensor: shape=(2, 4), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702,  0.07595026, -1.2573844 ],
       [-0.23193763, -1.8107855 ,  0.09988727, -0.50998646]],
      dtype=float32)>

NOTE:-If both the global and the operation seed are set: Both seeds are used in conjunction to determine the random sequence.

In [ ]:
tf.random.shuffle(tensor_random4)

<tf.Tensor: shape=(2, 4), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702,  0.07595026, -1.2573844 ],
       [-0.23193763, -1.8107855 ,  0.09988727, -0.50998646]],
      dtype=float32)>

In [ ]:
##tf.random.set_seed(42)
tf.random.shuffle(tensor_random4, seed=42)

<tf.Tensor: shape=(2, 4), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702,  0.07595026, -1.2573844 ],
       [-0.23193763, -1.8107855 ,  0.09988727, -0.50998646]],
      dtype=float32)>

In [ ]:
## Tensors from Numpy
tf.ones([3,4])

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]], dtype=float32)>

In [ ]:
tf.zeros(shape=(4,3))

<tf.Tensor: shape=(4, 3), dtype=float32, numpy=
array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]], dtype=float32)>

In [ ]:
import numpy as np
n1=np.arange(1,25, dtype=np.int32)
n1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [ ]:
t1=tf.constant(n1)
t1

<tf.Tensor: shape=(24,), dtype=int32, numpy=
array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)>

In [ ]:
t1=tf.constant(n1, shape=(4,2,3))
t1

<tf.Tensor: shape=(4, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24]]], dtype=int32)>